### ISSUE TITLE
Awesome project

### ISSUE THREAD

**Issue by vcapretz** [MicheleBertoli/react-automata#20]
Just coming here to tell you: awesome project, first tests with it showed good results on the project I'm working on! 

We were kinda of implementing it by hand on that project, just reinventing the wheel.

I'm probably going to send a PR to it (https://github.com/pagarme/artis) proposing the usage of react-automata 

*Question*: is there a scheduled time for launching the next version on `npm`? I saw that it is out of date 

🎉

(this is not a issue, just a thank note, feel free to close it after reading)

**Comment by ferdinandsalis** [comment]
@vcapretz you can get the newest one via `yarn add react-automata@next`.

Also, I agree this state machine thing is great and so is react-automata 😄

**Comment by davidkpiano** [comment]
If any of you have suggestions/feature requests (especially if you worked with UML/statecharts before), feel free to post an issue [on the `xstate` repo](https://github.com/davidkpiano/xstate/issues) as well - that way it can make its way into `react-automata` quicker 😄

**Comment by MicheleBertoli** [comment]
@vcapretz thank you very much for taking time and writing this note, I really appreciate it.
I can confirm `yarn add react-automata@next` is the best way to get what's on master right now, and I'll also push v1 ASAP.
Please let me know whether you have any feedback or experience any issue using the package, I'll be more than happy to help.

@ferdinandsalis thank you very much for your feedback and contribution.

@davidkpiano thank you very much - you are awesome. I'll try to find time to give back and contribute to `xstate` soon.

**Comment by vcapretz** [comment]
hey @MicheleBertoli, I found an use case that I don't know if I handled the best way:

I have different page navigation for desktop and mobile devices (I'm writing a responsive app), so when declaring the `statechart` I had to do some verification like this:

```js
states: {
    customer: {
      on: {
        NEXT: checkDesktop ? 'shipping' : 'billing',
      },
    },
    billing: {
      on: {
        PREV: 'customer',
        NEXT: 'shipping',
      },
    },
    shipping: {
      on: {
        PREV: checkDesktop ? 'customer' : 'billing',
        NEXT: 'payment',
      },
    },
   ......
```

do you think there's a better way to do it?

**Comment by MicheleBertoli** [comment]
@vcapretz all you need is [Gaurds](http://davidkpiano.github.io/xstate/docs/#/guides/guards). `xstate` is just awesome :)

**Comment by vcapretz** [comment]
closing this as it's now just keeping an open issue 😉🎉
