### ISSUE TITLE
Just an idea.. Storybook...

### ISSUE THREAD

**Issue by brikou** [MicheleBertoli/react-automata#23]
Having jest snapshots generated is really nice. What do you think about generating the same kind of thing for storybook ? Great lib ! Thanks :)

**Comment by brikou** [comment]
Your code is really easy to read and it should be really easy to do... Great !

**Comment by Baransu** [comment]
I've done some basic experiments with storybook. I was using almost exact the same approach as in `testStatechart`. Here is a repo with the example if you want to look more into it :)

https://github.com/Baransu/react-automata-storybook-test/blob/master/src/stories/index.js

**Comment by brikou** [comment]
@Baransu this is nice!

**Comment by MicheleBertoli** [comment]
That's a wonderful idea, thanks @Baransu.
And thanks @Baransu for experimenting on this..

It's out of the scope of this package, but I'll be more than happy to get involved in building a Storybook addon.
