### ISSUE TITLE
Add props, wrapper component in testStatechart

### ISSUE THREAD

**Issue by good-idea** [MicheleBertoli/react-automata#24]
Given:

```
import { testStatechart } from 'react-automata'
import { App, statechart } from './App'

test('it works', () => {
  testStatechart({ statechart }, App)
})
```

Is there any way to supply **App** with required props, or wrap it in a component like `<MemoryRouter/>`?

**Comment by MicheleBertoli** [comment]
Hello @good-idea, thanks for opening the issue.

The required props can be passed using the fixtures as follows:

```diff
 import { testStatechart } from 'react-automata'
 import { App, statechart } from './App'

+const fixtures = {
+  initialData: {
+    gists: [
+      {
+        id: 'ID1',
+        description: 'GIST1',
+      },
+      {
+        id: 'ID2',
+        description: 'GIST2',
+      },
+    ],
+  },
+}
+
 test('it works', () => {
-  testStatechart({ statechart }, App)
+  testStatechart({ statechart, fixtures }, App)
 })
```

At the moment is not possible to wrap the tested component, and I recommend you avoid doing it.
In theory, your components should work by themselves and if they don't, I'd suggest you mock their dependencies.

I hope this helps.

**Comment by good-idea** [comment]
great, thank you!
