### ISSUE TITLE
How to access machine outside React component ?

### ISSUE THREAD

**Issue by gcazaciuc** [MicheleBertoli/react-automata#28]
Hello,
First of all thanks for the project, it's an awesome library. I'm wondering how can one access the machine outside of a React component?
The use case is this:
I have a state machine used to orchestrate an UI flow. The state machine needs to do transitions based on events happening outside a certain React component, eg in a Mobx store, when the route changes etc.
Also the machine receives events from a top level React view.
I'm thinking the library would be much more flexible if it could accept either a state chart spec like it does now or a xtstate Machine object created outside the library.
Ideally i should be able to create the machine based on the state chart and pass it to the component.

Please let me know your thoughts.

**Comment by davidkpiano** [comment]
Ideally a machine's definition can be defined as a `static` value of the component class - just an idea.

**Comment by MicheleBertoli** [comment]
Thank you very much @gcazaciuc for opening this issue.
Accepting both a configuration or an existing machine seems a good idea, and I also like @davidkpiano's suggestion of defining a `static` property.
For your use-case, I think the first solution (passing a machine) would be ideal. 
Would you be happy to submit a PR?

**Comment by gcazaciuc** [comment]
Yes, thank you, I will work on a pr for it.

**Comment by MicheleBertoli** [comment]
Merged #29 🙌
Thank you very much, @gcazaciuc.
