### ISSUE TITLE
Strict mode

### ISSUE THREAD

**Issue by MicheleBertoli** [MicheleBertoli/react-automata#3]
Add a `strict` option which makes the component throw an exception if the current state doesn't support the action.
```js
withStateMachine({ config, strict: true })(App)
```

**Comment by ctrlplusb** [comment]
Or if a state isn't represented within the component? 😇

**Comment by davidkpiano** [comment]
@MicheleBertoli I can also add strict mode to error for undefined state transitions in xstate version 2 if that's desirable. 

Currently (in the beta), `.transition(state, unhandledAction)` will return `undefined`.

**Comment by MicheleBertoli** [comment]
Oh yeah @ctrlplusb, thanks for your comment.
I was thinking about "registering" the `State` components to the parent, in order to double check that all the states are covered.

---

That'd be great, thank you very much @davidkpiano.
The current beta behaviour with the `undefined` state makes it easy to throw an exception within this package.
However, I believe `xstate` users would benefit from a strict mode as well and the more `react-automata` is just a React/UI layer on top of existing `xstate` features, the better.

**Comment by MicheleBertoli** [comment]
Fixed in https://github.com/davidkpiano/xstate/issues/23
