### ISSUE TITLE
Initialising a machine with a different initial state is inert

### ISSUE THREAD

**Issue by ferdinandsalis** [MicheleBertoli/react-automata#30]
Currently when you want to initialise a Machine with a different state than specified in the statechart the resulting state is inert and might lack necessary information to be useful to render an ui. That is `actions` and `history` (maybe more in the future eg. `data`).

Might it be better to able to pass a state object such as from `new State(stateValue, history?, actions?)` to the `withStatechart` decorated component?

My use case is as stated in this issue https://github.com/davidkpiano/xstate/issues/31.

**Comment by ferdinandsalis** [comment]
I guess this also necessitates that one is able to get the current `State` object. However currently you can only get the `StateValue`.

**Comment by MicheleBertoli** [comment]
Thank you very much, @ferdinandsalis.
I left a comment on the PR.

> I guess this also necessitates that one is able to get the current State object. However currently you can only get the StateValue.

100% agree, I also need to change this behaviour for a component I'm working on.
I'll push an update very soon.

**Comment by MicheleBertoli** [comment]
Here we go: https://github.com/MicheleBertoli/react-automata/commit/895b4fc33df798f5b8b50f97a2c21a6beeefa9ee :)

**Comment by ferdinandsalis** [comment]
@MicheleBertoli awesome just what I needed ☺️

**Comment by MicheleBertoli** [comment]
Merged #31 🙌
Thank you very much, @ferdinandsalis.
