### ISSUE TITLE
Crash with react-native-debugger

### ISSUE THREAD

**Issue by fernandofranca** [MicheleBertoli/react-automata#34]
`react-native-debugger` packs Redux Devtools and when a component wrapped with `withStatechart` unmounts, an error will be thrown due `window.__REDUX_DEVTOOLS_EXTENSION__.disconnect` being unavailable.

Checking if the function is available should fix it: https://github.com/fernandofranca/react-automata/commit/b04b969bb89f2b76fa3038ab26740d932a2607d4?diff=split

**Comment by MicheleBertoli** [comment]
Thank you very much @fernandofranca for opening this issue.
I'm not familiar with `react-native-debugger`, but the `disconnect` method should exist in `__REDUX_DEVTOOLS_EXTENSION__ ` (as described in the [docs](http://extension.remotedev.io/docs/API/Methods.html#disconnect)).
I recommend you open an issue in that package's repo and help make the API fully compatible.
I hope this makes sense for you.

**Comment by fernandofranca** [comment]
Just in case, if anyone needs a simple solution:
```
if (window.__REDUX_DEVTOOLS_EXTENSION__ && 
  !window.__REDUX_DEVTOOLS_EXTENSION__.disconnect){
  window.__REDUX_DEVTOOLS_EXTENSION__.disconnect = () => {}
}
```
