### ISSUE TITLE
Animated Action

### ISSUE THREAD

**Issue by Dervanil** [MicheleBertoli/react-automata#42]
Hi, first I would to say that this is an awesome project!

I have a question, it's possible to create a version of Action that has animation integrate within it?
I thought in using [react-transition-group](https://github.com/reactjs/react-transition-group) to simplify, if you guide me I can submit a PR or whatever you think is appropriate.

Thanks in advance.

**Comment by MicheleBertoli** [comment]
Hello @Dervanil, thanks for opening this issue.

Both `Action` and `State` components support render props.
The function gives you a boolean that tells you whether the action (or the state) matches.
In this way, you can use `ReacTransitionGroup` (or any other component) to build animations.

For example:

```js
<Action 
  render={visible => <Transition in={visible} timeout={500} />}
  show="myAction" 
/>
```

I hope this helps.

**Comment by Dervanil** [comment]
Thank you Michele, that's exactly what I was looking for.
