### ISSUE TITLE
Link to Ryan Florence video does not exist any more

### ISSUE THREAD

**Issue by mukeshsoni** [MicheleBertoli/react-automata#43]
The link to Ryan Florence video in the footer of README does not exist any more - https://www.youtube.com/watch?v=MkdV2-U16tc

**Comment by MicheleBertoli** [comment]
Oh, that video was pretty awesome - It looks like it's been removed.
Good catch, I updated the README.
Thank you very much @mukeshsoni.

**Comment by ShMcK** [comment]
This link can now be found here: https://www.youtube.com/watch?v=WbhpQXH7XMw

**Comment by MicheleBertoli** [comment]
Thank you very much @ShMcK I updated the README.

**Comment by mukeshsoni** [comment]
Thanks @ShMcK !
