### ISSUE TITLE
How to test conditional transitions?

### ISSUE THREAD

**Issue by hally9k** [MicheleBertoli/react-automata#49]
How can I set the `extendedState` for a [guarded transition](http://davidkpiano.github.io/xstate/docs/#/guides/guards) in my testing fixtures?

**Comment by davidkpiano** [comment]
I'm working on a solution for that in `xstate` currently, so once that's done (likely in `3.3`) I'll make a PR to upgrade the tests to handle conditional transitions in `react-automata`.

**Comment by MicheleBertoli** [comment]
Thank you very much @hally9k @davidkpiano.

`react-automata` is already passing the fixtures to `xstate`'s `transition` as a third parameter (see [here](https://github.com/MicheleBertoli/react-automata/blob/master/src/testStatechart.js#L25) and [here](https://github.com/MicheleBertoli/react-automata/blob/master/src/withStatechart.js#L126)).
However, `xstate`'s `getShortestPaths` doesn't seem to return states guarded by conditions (see [here](https://github.com/davidkpiano/xstate/blob/master/src/graph.ts#L77)).

For example:

```js
const statechart = {
  initial: 'a',
  states: {
    a: {
      on: {
        EVENT: {
          b: {
            cond: extState => extState.shouldPass,
          },
        },
      },
    },
    b: {},
  },
}
const machine = Machine(statechart)
const paths = getShortestPaths(machine)

// { '"a"': [] }
```

**Comment by MicheleBertoli** [comment]
Sure @davidkpiano, here it is: https://github.com/davidkpiano/xstate/issues/100.
Thank you very much!

**Comment by MicheleBertoli** [comment]
Given the following statechart:

```js
const statechart = {
  initial: 'a',
  states: {
    a: {
      on: {
        EVENT: {
          b: {
            cond: extState => extState.shouldPass,
          },
        },
      },
    },
    b: {},
  },
}
```

and the following component:

```js
const Cond = () => (
  <React.Fragment>
    <State value="a">A</State>
    <State value="b">B</State>
  </React.Fragment>
)
```

it's now possible to write a test that passes the condition:

```js
test('pass', () => {
  const extendedState = {
    shouldPass: true,
  }
  const fixtures = {
    a: {
      EVENT: extendedState,
    },
  }

  testStatechart({ statechart, fixtures, extendedState }, Cond)
})
```

```js
exports[`cond pass: a 1`] = `"A"`;
```

```js
exports[`cond pass: b 1`] = `"B"`;
```

and one that doesn't:

```js
test('fail', () => {
  testStatechart({ statechart }, Cond)
})
```

```js
exports[`cond fail: a 1`] = `"A"`;
```

Thank you very much, @hally9k @davidkpiano.
