### ISSUE TITLE
Shrink Import Size, restructure dependencies

### ISSUE THREAD

**Issue by ShMcK** [MicheleBertoli/react-automata#56]
Currently react-automata is coming in at 87.9KB (27.3KB gzipped).

Considering React comes in at 7.7KB (3.3KB gzipped), this seems a bit large.

---

It may be worth moving some dependencies into "devDependencies" or "peerDependencies" where it makes sense.

```json
{
  "dependencies": {
    "glob-to-regexp": "^0.4.0",
    "invariant": "^2.2.4",
    "prop-types": "^15.6.1",
    "react-test-renderer": "^16.4.0",
    "xstate": "^3.3.0"
  }
}
```

### React Test Renderer

In this case, the "react-test-renderer" locks in to a specific version of React (v16.4+). This is bound to cause some conflicts and would probably be better suited as a "peerDependency".

### Prop Types
"prop-types" may be better suited as devDependencies.

**Comment by davidkpiano** [comment]
This would make a great PR. Want to help with that? 😄

**Comment by ShMcK** [comment]
Will do :)
