### ISSUE TITLE
Give a way to update data (without  transition)

### ISSUE THREAD

**Issue by palashkaria** [MicheleBertoli/react-automata#58]
This is more of a question, hence an issue not a PR. 

I see a lot of use cases where I need to do update the state outside of a transition. It might just be because I'm doing something wrong, but how about an `this.props.updateData({} || updater)` that gets passed down, similar to second arg of transition. we can event give it a callback, `updateData = ({}, callback) => this.setState({}, callback)`. Any potential problems with this approach?

**Comment by davidkpiano** [comment]
If you think about what is happening when you need to update state, some `event` occurs that causes the state to need to update. Since it's better to keep track of each state change in response to an event (especially for testing purposes), I'd argue that your best bet would be to use a self-transition:

```js
{
  foo: {
    on: {
	  SOME_EVENT: {
		target: 'foo',  // self-transition
		actions: ['updateStateHere']
	  }
    }
  }
}
```

**Comment by palashkaria** [comment]
I get that, but even if I do this, how do I update the machine's data in `updateStateHere`? I can only do it in `transition('SOME_EVENT', { data })` .(Consider the case when transition event is named something generic, like 'NEXT')

**Comment by MicheleBertoli** [comment]
Thank you very much for your opening this issue @palashkaria, and thanks for your comment @davidkpiano.

I understand your question, but I 100% agree with @davidkpiano:

> If you think about what is happening when you need to update state, some event occurs that causes the state to need to update. 

I recommend you check why you feel the need to update the state without performing a transition.
Feel free to reopen the issue if you are happy to share/discuss your use-case.
