### ISSUE TITLE
Invariant violation error when componentState changed but not machineState

### ISSUE THREAD

**Issue by dangh** [MicheleBertoli/react-automata#71]
Re-pro: https://codesandbox.io/s/ook0p3y23z

If you click on <kbd>-> b with error</kbd> button, the flag is locked and you cannot click on <kbd>-> b</kbd> button anymore.

I trace down to these methods:

In `handleTransition()`, `this.isTransitioning` is turned on
https://github.com/MicheleBertoli/react-automata/blob/dbebfba07987b159670c7b9890f01a687ce2f715/src/withStateMachine.js#L152-L161 

In `handleComponentDidUpdate()`, it supposed to be turned off but it does not because the machineState doesn't change.
https://github.com/MicheleBertoli/react-automata/blob/dbebfba07987b159670c7b9890f01a687ce2f715/src/withStateMachine.js#L117-L119

So when another transition triggered, the invariant guard yielded.

**Comment by MicheleBertoli** [comment]
Good catch, thanks for opening this issue and providing a non-working example. @dangh.
The issue is fixed in `v4.0.3`.
