### ISSUE TITLE
Is testStateMachine code included in prod builds?

### ISSUE THREAD

**Issue by san650** [MicheleBertoli/react-automata#73]
Hi,

Thanks for the library, it's awesome!

I've started using the library to model a small state machine for a react app and I believe that when doing a production build of my app, the testStateMachine code is included in it. (I'm using webpack to build my app).

Can this be the case?

If it's not the case, sorry for the confusion. In case this is happening, is there a way to prevent this?

This is just a guess, but I think this happens because `./src/testStateMachine.js` is required from `./src/index.js`. Maybe this could be change to allow users to import it explicitly in the application code with something like

```js
import testStateMachine from "react-automata/testStateMachine"
```

making the file optional for users, in my case, I want to include it only in dev/test builds.

Let me know if you would accept a PR for making this happen 😃 .

**Comment by MicheleBertoli** [comment]
Thank you very much for opening this issue, @san650.
I confirm that `testStateMachine` is included in the bundle, and we are discussing possible solutions in https://github.com/MicheleBertoli/react-automata/issues/32.

Let me close this, in favour of the other one, and please feel free to contribute to the discussion.

**Comment by san650** [comment]
@MicheleBertoli Thanks for your quick reply! I'll follow the conversation in #32
