### ISSUE TITLE
Upgrade guide for v4

### ISSUE THREAD

**Issue by kriswep** [MicheleBertoli/react-automata#78]
Since v4 had some API changes and renaming, I was looked for an upgrade guide.
Only thing I found was the changelog. That could be a little bit clearer.
Are you interested in a Upgrading Documentation PR? Especially from 3.x.x to 4.x x?
If yes, I could send a PR in the hacktoberfest spirit.

**Comment by MicheleBertoli** [comment]
Thank you very much, @kriswep.
Documentation is always welcome, I'm looking forward to receiving a PR.

❤️#hacktoberfest
