### ISSUE TITLE
Future plans for react automata

### ISSUE THREAD

**Issue by ferdinandsalis** [MicheleBertoli/react-automata#82]
Hi Michele,

I am curious **if and how** you are going to evolve this library in the coming month. I am sure there some new interesting ways to do things with the changes recently introduced to react and xstate. Anyway, just dropping by to say that I am happily using react automata in two of my projects and look forward to all the things statecharts and react that are happening.

👋 Ferdinand

**Comment by davidkpiano** [comment]
I'll be making a pull request 🔜 to get XState V4 integrated into React Automata, so it can get all the new features.

**Comment by MicheleBertoli** [comment]
Thank you very much for opening this issue, @ferdinandsalis.
I really appreciate your feedback, and I'm glad you enjoy using this library.

I saw @davidkpiano's [awesome talk](https://www.youtube.com/watch?v=DrHccvns-L0) at the ReactiveConf, but I didn't have time to play around with v4 yet.

I'm open to suggestions, and I'll be happy to review a PR :)

**Comment by davidkpiano** [comment]
Just an update: I'll have the PR by today.

EDIT: Bigger task than expected 😓 it would be a huge change.

**Comment by famulus** [comment]
> EDIT: Bigger task than expected 😓 it would be a huge change.

Bummer!  What are some of the challenges?

**Comment by davidkpiano** [comment]
> Bummer! What are some of the challenges?

The way that `react-automata` handles executing actions is a bit different than how the XState built-in interpreter handles them. Not sure how to remedy this besides changing many files and ripping out a lot of code.

For reference, here is how XState can be added in React projects (using classes or hooks): https://xstate.js.org/docs/recipes/react.html
